// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEoHKfW-SXEAo3G6tZBmsPcbQLWg83maQ',
    appId: '1:1067630356577:web:59fcdb833a6af8d7bfa220',
    messagingSenderId: '1067630356577',
    projectId: 'feedbackflow-daf0f',
    authDomain: 'feedbackflow-daf0f.firebaseapp.com',
    storageBucket: 'feedbackflow-daf0f.appspot.com',
    measurementId: 'G-3366JVMVLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAQVdDVtRjss9kMNo8X1xEbBdrfV9x_dY',
    appId: '1:1067630356577:android:1756f09b0a879022bfa220',
    messagingSenderId: '1067630356577',
    projectId: 'feedbackflow-daf0f',
    storageBucket: 'feedbackflow-daf0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRdrO986cQeC0A_2geo2HBu7daJv555MM',
    appId: '1:1067630356577:ios:8c68bbc4ed0d8aadbfa220',
    messagingSenderId: '1067630356577',
    projectId: 'feedbackflow-daf0f',
    storageBucket: 'feedbackflow-daf0f.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRdrO986cQeC0A_2geo2HBu7daJv555MM',
    appId: '1:1067630356577:ios:4db4ff4eb16ee302bfa220',
    messagingSenderId: '1067630356577',
    projectId: 'feedbackflow-daf0f',
    storageBucket: 'feedbackflow-daf0f.appspot.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
